# Generated by Django 5.0.1 on 2024-01-05 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizzes"},
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={"verbose_name_plural": "User's Answer"},
        ),
    ]
