# Generated by Django 5.0 on 2024-02-04 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_quiz_options_alter_useranswer_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="selected_option",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="user",
        ),
        migrations.AddField(
            model_name="question",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="level",
            field=models.CharField(
                choices=[("Hard", "Hard"), ("Easy", "Easy"), ("Normal", "Normal")],
                default=None,
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="number_of_question",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="time",
            field=models.TimeField(default=None, help_text="Time for quiz in minutes"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=200)),
                ("correct", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="main.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.quiz"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="UserAnswer",
        ),
    ]
